<a href="https://colab.research.google.com/github/meetAmarAtGithub/Guvi/blob/main/DL%5C1_Getting_started.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color="blue">Python basics: Tuples, Sets, Dictionaries</font>

# *Tuple*



In [ ]:
my_phone_tuple = ('I phone 5', False, 3)
print(my_phone_tuple)

('I phone 5', False, 3)


In [ ]:
my_phone_tuple[0]

'I phone 5'

In [ ]:
my_phone_tuple[0:2]

('I phone 5', False)

In [ ]:
for data in my_phone_tuple:
  print(data)

I phone 5
False
3


In [ ]:
import time
tic = time.time()
toc = time.time()
print('Elapsed time', toc - tic)

Elapsed time 6.031990051269531e-05


# proof tuple execution is faster

In [ ]:
my_list = list(range(10000000))
tic = time.time()
my_list_squared = map(lambda i : i ** 2, my_list)
toc = time.time()
list_toc = toc - tic
print('Elapsed time in seconds', list_toc)

Elapsed time in seconds 0.00015783309936523438


In [ ]:
my_tuple = tuple(range(10000000))
tic = time.time()
my_list_squared = map(lambda i : i ** 2, my_tuple)
toc = time.time()
tuple_toc = toc - tic
print('Elapsed time in seconds',  tuple_toc)

Elapsed time in seconds 0.00010371208190917969


In [ ]:
if tuple_toc > list_toc:
  print('Tuple is slower than list')
else:
  print('Tuple is faster than list')

Tuple is faster than list


# Sets

In [ ]:
my_set = set(my_list[0:30])
print(my_set)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29}


In [ ]:
my_list = ['IPhone',4.3,False,4.3]
print(my_list)

['IPhone', 4.3, False, 4.3]


In [ ]:
#set returns unique items in list / tuple
my_set = set(my_list)
print(my_set)

{False, 4.3, 'IPhone'}


# Dictionary

In [ ]:
my_phone_dict = {}
print(type(my_phone_dict))

<class 'dict'>


In [ ]:
my_phone_dict['name'] = 'Iphone 5s'
my_phone_dict['isAndriod'] = False
my_phone_dict['screenSize'] = 4.3
print(my_phone_dict)

{'name': 'Iphone 5s', 'isAndriod': False, 'screenSize': 4.3}


In [ ]:
my_phone_dict['name']

'Iphone 5s'

In [ ]:
print(my_phone_dict.keys())

dict_keys(['name', 'isAndriod', 'screenSize'])


In [ ]:
print(my_phone_dict.values())

dict_values(['Iphone 5s', False, 4.3])


In [ ]:
print(my_phone_dict.items())

dict_items([('name', 'Iphone 5s'), ('isAndriod', False), ('screenSize', 4.3)])


In [ ]:
for key in my_phone_dict.keys():
  print(key, my_phone_dict[key])

name Iphone 5s
isAndriod False
screenSize 4.3


# <font color="blue"> Python Baics : Packages </font>

In [ ]:
import math

In [ ]:
print(math.sqrt(100))

10.0


In [ ]:
print(math.pow(100,0.5))

10.0


Math Library provides lots of in built functions

In [ ]:
#For example of to calculate factorial of 100 
x = 100
y = 1
for i in range(1, x):
  y *= i
print('Factorial of x is - ', x , ' is ', y)

Factorial of x is -  100  is  933262154439441526816992388562667004907159682643816214685929638952175999932299156089414639761565182862536979208272237582511852109168640000000000000000000000


In [ ]:
#Using math function it is just one linear code
print(math.factorial(x))

93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000


In [ ]:
from math import factorial
print(factorial (x))

93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000


In [ ]:
vals = list(range(1,100))
tic = time.time()
for x in vals:
  y = 1
  for i in range(1,x):
    y *= i
toc = time.time()
ownFuncTime = toc - tic
print('Time elapsed in seconds with own function', ownFuncTime)

tic = time.time()
for x in vals:
  y = factorial(x)
toc = time.time()
FunctionTimeDiff = toc - tic
print('Time elapsed in seconds with own function', FunctionTimeDiff)

if(FunctionTimeDiff > ownFuncTime):
  print('Own function is faster')
else:
  print('Math functions are faster')

Time elapsed in seconds with own function 0.0023925304412841797
Time elapsed in seconds with own function 0.0002181529998779297
Math functions are faster


# Use your own package

In [ ]:
!echo 'def hello():' > my_first_module.py
!echo '  print("Hello, I am living in a different file!!!!")' >> my_first_module.py

In [ ]:
!cat my_first_module.py

def hello():
  print("Hello, I am living in a different file!!!!")


In [ ]:
#In order to use this file in your code, import it first
import my_first_module
my_first_module.hello()

Hello, I am living in a different file!!!!


In [ ]:
from my_first_module import hello
hello()

Hello, I am living in a different file!!!!


#File Handling

In [ ]:
!wget https://raw.githubusercontent.com/likhitha9reddy/PadhAI/master/mobile_cleaned.csv

--2022-10-24 10:35:54--  https://raw.githubusercontent.com/likhitha9reddy/PadhAI/master/mobile_cleaned.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14044 (14K) [text/plain]
Saving to: ‘mobile_cleaned.csv’

mobile_cleaned.csv  100%[===================>]  13.71K  --.-KB/s    in 0s      

2022-10-24 10:35:54 (85.7 MB/s) - ‘mobile_cleaned.csv’ saved [14044/14044]



In [ ]:
!ls

mobile_cleaned.csv  my_first_module.py	__pycache__  sample_data


In [ ]:
files = open('mobile_cleaned.csv','r')

In [ ]:
s = files.readline()

In [ ]:
print(s)

sim_type,aperture,gpu_rank,weight,stand_by_time,processor_frequency,thickness,flash_type,front_camera_resolution,auto_focus,screen_size,frames_per_second,FM,no_of_reviews_in_gsmarena_in_week,os,phone_height,screen_protection,sim_size,price,talk_time,video_resolution,display_resolution,removable_battery,display_type,primary_camera_resolution,battery_type,ram_memory,internal_memory,brand_rank,no_of_cores,micro_sd_slot,screen_pixel_density,water_proof_rate,phone_width,expandable_memory,version,usb_type,battery_capacity,processor_rank,is_liked



In [ ]:
print(s.split(','))

['sim_type', 'aperture', 'gpu_rank', 'weight', 'stand_by_time', 'processor_frequency', 'thickness', 'flash_type', 'front_camera_resolution', 'auto_focus', 'screen_size', 'frames_per_second', 'FM', 'no_of_reviews_in_gsmarena_in_week', 'os', 'phone_height', 'screen_protection', 'sim_size', 'price', 'talk_time', 'video_resolution', 'display_resolution', 'removable_battery', 'display_type', 'primary_camera_resolution', 'battery_type', 'ram_memory', 'internal_memory', 'brand_rank', 'no_of_cores', 'micro_sd_slot', 'screen_pixel_density', 'water_proof_rate', 'phone_width', 'expandable_memory', 'version', 'usb_type', 'battery_capacity', 'processor_rank', 'is_liked\n']


In [ ]:
files.close()

Another approach to access a file

In [ ]:
with open('mobile_cleaned.csv','r') as file:
  print(file.readline())

sim_type,aperture,gpu_rank,weight,stand_by_time,processor_frequency,thickness,flash_type,front_camera_resolution,auto_focus,screen_size,frames_per_second,FM,no_of_reviews_in_gsmarena_in_week,os,phone_height,screen_protection,sim_size,price,talk_time,video_resolution,display_resolution,removable_battery,display_type,primary_camera_resolution,battery_type,ram_memory,internal_memory,brand_rank,no_of_cores,micro_sd_slot,screen_pixel_density,water_proof_rate,phone_width,expandable_memory,version,usb_type,battery_capacity,processor_rank,is_liked



In [ ]:
with open('mobile_cleaned.csv','r') as file:
  print(file.read())

In [ ]:
with open('mobile_cleaned.csv','r') as file:
  for line in file:
    print(line)

In [ ]:
with open('mobile_cleaned.csv','r') as file:
  for line in file:
    for word in line.split(','):
      print(word)
    print('================')

### Write to a file

In [ ]:
with open ('my_first_file_output.txt','w') as file:
  file.write('Hello world from python code')

In [ ]:
!cat my_first_file_output.txt

Hello world from python code

#Python Classes

In [ ]:
class MobilePhone:
  """This is a sample class to demonstrate how python classes work"""
  def __init__(self, name, is_android=False, screen_size = 4.3):
    self.name = name
    self.is_android = is_android
    self.screen_size = screen_size
    self.rating = -1
  def has_rating(self, rating):
    return self.rating > rating

In [ ]:
new_phone = MobilePhone('IPhone 5s')

In [ ]:
new_phone.name

'IPhone 5s'

In [ ]:
new_phone.is_android

False

In [ ]:
new_phone.screen_size

4.3

In [ ]:
new_phone.screen_size = 4

In [ ]:
new_phone.has_rating(1)

False

In [ ]:
new_phone.rating = 3.5

In [ ]:
new_phone.has_rating(3)

True

In [ ]:
MobilePhone.__doc__

'This is a sample class to demonstrate how python classes work'

### Inheritence in Python

In [ ]:
class iPhone(MobilePhone):
  def __init__(self, name):
    MobilePhone.__init__(self, name, False, 4)

  def __str__(self):
    return self.name + " " + str(self.is_android) + " " + str(self.screen_size)


In [ ]:
new_phone = iPhone('IPhone 11')

In [ ]:
new_phone.is_android

False

In [ ]:
#This will invoke str function of iPhone class
print(new_phone)

IPhone 11 False 4


# Numpy (Num stands for Numerical and Py stands for Python)

In [2]:
import numpy as np

In [ ]:
x = np.array([1,2,3])
print(x)

[1 2 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
#Converting a list into Numpy array
i = [4,6,10]
x = np.asarray(i)
type(x)

numpy.ndarray

In [ ]:
#while converting to np array it can be converted into float
x = np.asarray(i,float)
print(x)

[ 4.  6. 10.]


In [ ]:
x.shape

(3,)

In [ ]:
np.array?

In [ ]:
#Create two dmensional array
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
x.shape

(3, 3)

In [ ]:
#Access elements of two dimensional array
x[0,0]

1

In [ ]:
#Access 2nd and 3rd element of 3rd array 
print(x[2 , 1:3])

[8 9]


In [ ]:
#Access all elements of second array
print(x[1, :])

[4 5 6]


In [ ]:
#create a 4 X 5 zeroes matrix
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#Create an identity matrix
x = np.eye(4,4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#Create an array of random number
x = np.random.random((4,5))
print(x)

[[0.32847819 0.43042057 0.94403511 0.81743982 0.1605277 ]
 [0.49067961 0.04746119 0.24705169 0.83666234 0.23522817]
 [0.44076359 0.52542904 0.17619774 0.42125677 0.98289551]
 [0.95442771 0.21539102 0.92073337 0.54896035 0.08590125]]


In [ ]:
#Transpose of Matrix
z = x.T
print(z)

[[0.32847819 0.49067961 0.44076359 0.95442771]
 [0.43042057 0.04746119 0.52542904 0.21539102]
 [0.94403511 0.24705169 0.17619774 0.92073337]
 [0.81743982 0.83666234 0.42125677 0.54896035]
 [0.1605277  0.23522817 0.98289551 0.08590125]]


In [ ]:
#Reshape Matrix
y = z.reshape(10,2)
print(y)

[[0.32847819 0.49067961]
 [0.44076359 0.95442771]
 [0.43042057 0.04746119]
 [0.52542904 0.21539102]
 [0.94403511 0.24705169]
 [0.17619774 0.92073337]
 [0.81743982 0.83666234]
 [0.42125677 0.54896035]
 [0.1605277  0.23522817]
 [0.98289551 0.08590125]]


In [17]:
#Arange function
A = np.arange(5)
print(A)

[0 1 2 3 4]


In [18]:
B = np.arange(5)

In [ ]:
print(A + B)

[0 2 4 6 8]


In [ ]:
print(A - B)

[0 0 0 0 0]


In [ ]:
print( A * B)

[ 0  1  4  9 16]


In [ ]:
#Broadcasting in python
#Here A is vector and 1 is scalar, but pyton has broadcasting feature by which scalar value is added to each element of v
print(A , A + 1)

[0 1 2 3 4] [1 2 3 4 5]


In [ ]:
#Scalar value can be added for two dimensional arrray as well
A = np.random.random((2,3))
print(A)
print(A + 1) #Broad casting

[[0.91844129 0.57760578 0.18096134]
 [0.43525345 0.93392322 0.9744738 ]]
[[1.91844129 1.57760578 1.18096134]
 [1.43525345 1.93392322 1.9744738 ]]


In [ ]:
A = np.floor(np.random.random((2,3))*10)
print(A)

[[6. 8. 4.]
 [8. 7. 9.]]


In [7]:
#Algebric operation
u = [1,2,3]
v = [-1, 0 ,1]

#inner product multiply element wise and add them 1 * -1 + 2 * 0 + 3 *1
pl = np.inner(u , v)
print(pl)

print()
print()

# outer product 1 with v, 2 with v , 3 with v
p2 = np.outer( u , v)
print(p2)

2


[[-1  0  1]
 [-2  0  2]
 [-3  0  3]]


In [8]:
#Dot product
print(np.dot(u, v))

2


In [9]:
#Sum array elements
print(np.sum(u))

6


In [12]:
#Columnwise sum
np.asarray(u).sum(axis=0)

6

In [19]:
#Row wise sum
A.sum(axis=1)

AxisError: ignored